### PR TITLE
Added kgnar events 

### PR DESCRIPTION
**Pull request by dy-dx-1**
I'm tired and not sure I did the attachement of the cog correctly so pls check over that (setup at the end of Events file) 

Checks for different types of messages from kgnar and should respond accordingly. Haven't tested it so might have to do some debugging!

### CODE REVIEW

**Comment by etanase** [comment]
Alright, I'll look over it later. I'd recommend making a quick bot and testing it in a private server (with your id) if you haven't already.

**Comment by etanase** [comment]
@dy-dx-1 Looks good, but since you haven't tested it please test it on a private server. I have to manually move new files onto the machine running the bot, so I'd like to only use tested code on that machine. You only have to test the cog, since the whole bot requires a database connection. Send proof of it working and I will merge.

**Comment by dy-dx-1** [comment]
Alright I will test it and let you know when I have time 👍

**Comment by dy-dx-1** [comment]
@meme8383  I tested it, made some minor changes and it's working on my machine. Here's a screenshot of it responding (I changed the kgnar id to mine) lmk if you need more 
image

**Comment by etanase** [comment]
I'll add it to the running instance soon

**Pull request merged**
